In [2]:
import pandas as pd
import sqlite3

df = pd.read_csv(r"C:\Users\SKHKUT001\OneDrive - University of Cape Town\Desktop\Kaggle\COVID-19 Twitter Data\Covid-19 Twitter Dataset (Apr-Jun 2020).csv")

conn = sqlite3.connect("covid_twitter.db")
df.to_sql("tweets", conn, if_exists="replace", index=False)

print("Data loaded into SQL!")

Data loaded into SQL!

In [3]:
query = "SELECT * FROM tweets LIMIT 5;"
pd.read_sql(query, conn)

,id,created_at,source,original_text,lang,favorite_count,retweet_count,original_author,hashtags,user_mentions,place,clean_tweet,compound,neg,neu,pos,sentiment
0,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/android"" ...",RT @GlblCtzn: .@priyankachopra is calling on l...,en,0.0,31.0,RJIshak,None,"GlblCtzn, priyankachopra",Jakarta Capital Region,call leader help protect refuge covid19 provid...,0.8176,0.0,0.452,0.548,pos
1,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/android"" ...",RT @OGSG_Official: OGUN STATE SUPPORT FOR CBN-...,en,0.0,61.0,makinwaoluwole,None,OGSG_Official,Nigeria,ogun state support cbn nirsal covid19 target c...,0.6486,0.0,0.602,0.398,pos
2,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/iphone"" r...",RT @AdvoBarryRoux: These 5 police officials ba...,en,0.0,1.0,TembeAmu,None,AdvoBarryRoux,None,polic offici base namahadi polic station busi ...,0.2732,0.0,0.851,0.149,pos
3,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/iphone"" r...",RT @MobilePunch: COVID-19: Oyo discharges two ...,en,0.0,0.0,ilyasrabiu,None,MobilePunch,"Lagos, Nigeria",covid19 oyo discharg two patient,0.0000,0.0,1.000,0.000,neu
4,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/android"" ...",My Condolences to the Family of those who did ...,en,0.0,13869.0,bucketeconomist,Covid_19,None,None,condol famili surviv,0.0000,0.0,1.000,0.000,neu

In [4]:
query = "SELECT COUNT(*) as total_tweets FROM tweets;"
pd.read_sql(query, conn)

   total_tweets
0        143903

In [6]:
pd.read_sql("PRAGMA table_info(tweets);", conn)

    cid             name  type  notnull dflt_value  pk
0     0               id  REAL        0       None   0
1     1       created_at  TEXT        0       None   0
2     2           source  TEXT        0       None   0
3     3    original_text  TEXT        0       None   0
4     4             lang  TEXT        0       None   0
5     5   favorite_count  REAL        0       None   0
6     6    retweet_count  REAL        0       None   0
7     7  original_author  TEXT        0       None   0
8     8         hashtags  TEXT        0       None   0
9     9    user_mentions  TEXT        0       None   0
10   10            place  TEXT        0       None   0
11   11      clean_tweet  TEXT        0       None   0
12   12         compound  REAL        0       None   0
13   13              neg  REAL        0       None   0
14   14              neu  REAL        0       None   0
15   15              pos  REAL        0       None   0
16   16        sentiment  TEXT        0       None   0

In [8]:
query = """
SELECT *
FROM tweets
WHERE original_text LIKE '%vaccine%'
LIMIT 10;
"""
pd.read_sql(query, conn)

,id,created_at,source,original_text,lang,favorite_count,retweet_count,original_author,hashtags,user_mentions,place,clean_tweet,compound,neg,neu,pos,sentiment
0,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/android"" ...",RT @BBCPolitics: The prospects of producing a ...,en,0.0,1009.0,PaigeForExample,None,BBCPolitics,"Dublin, Ireland 🇨🇮",prospect produc covid19 vaccin good say profes...,0.6249,0.000,0.662,0.338,pos
1,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/iphone"" r...",RT @GeigerNews: Fox News [snicker] personaliti...,en,0.0,5321.0,MattieAlford8,None,GeigerNews,None,fox news snicker person diamond silk say rejec...,0.2500,0.139,0.619,0.242,pos
2,1.250000e+18,2020-04-19,"<a href=""http://twitter.com/download/iphone"" r...",RT @TheSharpEdge1: FLASHBACK: Chief scientist ...,en,0.0,772.0,ItsMystery007,None,TheSharpEdge1,United States,flashback chief scientist lie public safeti va...,0.2023,0.000,0.847,0.153,pos
3,1.250000e+18,2020-04-19,"<a href=""http://www.peacefmonline.com"" rel=""no...",COVID-19: Gov't To Support Ghanaian Scientists...,en,0.0,7066.0,peacefmonline,None,None,Ghana,covid19 gov support ghanaian scientist develop...,0.4019,0.000,0.690,0.310,pos
4,1.250000e+18,2020-04-22,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @ChinaDaily: Is China's decision to lockdow...,en,0.0,690.0,ChinaEmbOttawa,None,ChinaDaily,"515 St. Patrick Street, Ottawa",china decis lockdown wuhan draconian western m...,0.0000,0.000,1.000,0.000,neu
5,1.250000e+18,2020-04-22,"<a href=""http://twitter.com/download/iphone"" r...",A doctor was removed because he believes Covid...,en,0.0,3381.0,crownyoqueennn,None,None,"Satellite Beach, FL",doctor remov belief covid19 scientif heal drug...,0.0000,0.000,1.000,0.000,neu
6,1.250000e+18,2020-04-22,"<a href=""https://mobile.twitter.com"" rel=""nofo...",RT @nancylevine: Trump removed top U.S. vaccin...,en,0.0,0.0,Concern93672193,None,nancylevine,United States,trump remov top vaccin scientist believ transf...,0.2023,0.000,0.833,0.167,pos
7,1.250000e+18,2020-04-22,"<a href=""http://twitter.com/download/iphone"" r...","RT @joshjame: ""You’d think after 39 years of b...",en,0.0,7.0,jvmnjp,None,joshjame,"Lititz, Pa",think year awar hiv studi vaccin,0.0000,0.000,1.000,0.000,neu
8,1.250000e+18,2020-04-22,"<a href=""http://twitter.com/download/iphone"" r...",RT @ddiamond: NEW: The complicated ouster of t...,en,0.0,1624.0,VedehiMajumdar,None,ddiamond,None,new complic ouster top vaccin scientist rick b...,0.2732,0.150,0.578,0.272,pos
9,1.250000e+18,2020-04-22,"<a href=""http://sarmadgardeziblog.blogspot.com...",RT @MashalArbab3: Prayers for the success of t...,en,0.0,0.0,goscips,"CoronaInPakistan, COVID19vaccine",MashalArbab3,Pakistan,prayer success clinic trial covid19 vaccin happen,0.5719,0.000,0.619,0.381,pos

In [9]:
query = """
SELECT 
    COUNT(CASE WHEN original_text LIKE '%vaccine%' THEN 1 END) AS vaccine,
    COUNT(CASE WHEN original_text LIKE '%lockdown%' THEN 1 END) AS lockdown,
    COUNT(CASE WHEN original_text LIKE '%government%' THEN 1 END) AS government
FROM tweets;
"""
pd.read_sql(query, conn)

   vaccine  lockdown  government
0     2081      3972        3810

In [10]:
query = """
SELECT *
FROM tweets
WHERE clean_tweet LIKE '%vaccine%'
LIMIT 10;
"""
pd.read_sql(query, conn)

Empty DataFrame
Columns: [id, created_at, source, original_text, lang, favorite_count, retweet_count, original_author, hashtags, user_mentions, place, clean_tweet, compound, neg, neu, pos, sentiment]
Index: []

In [11]:
query = """
SELECT sentiment, COUNT(*) AS count
FROM tweets
GROUP BY sentiment
ORDER BY count DESC;
"""
pd.read_sql(query, conn)

  sentiment  count
0       neu  57586
1       pos  46125
2       neg  40192

In [15]:
query = """
SELECT sentiment, COUNT(*) AS count
FROM tweets
WHERE clean_tweet LIKE '%vacc%'
GROUP BY sentiment;
"""
pd.read_sql(query, conn)

  sentiment  count
0       neg    374
1       neu   1155
2       pos    669

In [16]:
### What can we deduce from the above:

#- Total: (374 + 1155 + 669 = 2198)
#Negative (0): (374/2198)*100 = 17.0%
#Neutral (1): (1155/2198)*100 = 52,6%
#Positive (2): (669/2198)*100 = 30,4%

#
#COVID-19 vaccine-related discourse on Twitter is largely neutral (52.6%), which suggests that there is a high volume of informational content.
#Positive sentiment (30.4%) exceeds negative sentiment (17.0%), indicating generally favourable attitudes toward vaccination, although a non-trivial level of negative sentiment remains.

In [17]:
query = """
SELECT 
    'Vaccine' as topic, COUNT(*) as count
FROM tweets
WHERE clean_tweet LIKE '%vacc%'

UNION ALL

SELECT 
    'Lockdown', COUNT(*)
FROM tweets
WHERE clean_tweet LIKE '%lockdown%'

UNION ALL

SELECT 
    'Government', COUNT(*)
FROM tweets
WHERE clean_tweet LIKE '%government%';
"""
pd.read_sql(query, conn)

        topic  count
0     Vaccine   2198
1    Lockdown   3214
2  Government     15

In [ ]:
### What can we deduce from the above:

#COVID-19 discourse in this dataset is dominated by discussions around lockdown measures,...
#followed by vaccination, while direct references to government are minimal.


#- Total: (2198 + 3214 + 15 = 5427)
#Vaccine (0): (2198/5427)*100 = 40.5%
#Lockdown (1): (3214/5427)*100 = 59.2%
#Government (2): (15/5427)*100 = 0.3%


#Lockdown-related discourse dominates COVID-19 conversations (40.5%), suggesting that restrictive measures were the primary focus of public discussion.
#Vaccine-related discourse is also substantial (59.2%), while initial keyword searches suggest limited direct reference to government (0.3%);
#however, expanding keyword definitions is necessary to fully capture political discourse, highlighting the importance of robust Boolean query design in social listening analysis.

#The use of the word/term "government" may not give exact estimates.The following query will aim to use as many related search terms as possible

In [18]:
query = """
SELECT 
    'Government' as topic, COUNT(*) as count
FROM tweets
WHERE clean_tweet LIKE '%government%'
   OR clean_tweet LIKE '%president%'
   OR clean_tweet LIKE '%minister%'
   OR clean_tweet LIKE '%state%'
   OR clean_tweet LIKE '%authority%';
"""
pd.read_sql(query, conn)

        topic  count
0  Government   5308

In [ ]:
### What can we deduce from the above:

#Updated results: 0 (Vaccine) = 2198; 1 (Lockdown) = 3214; 2 (Government) = 5308


#- Total: (2198 + 3214 + 5308 = 10720)
#Vaccine (0): (2198/10720)*100 = 20.5%
#Lockdown (1): (3214/10720)*100 = 30.0%
#Government (2): (5308/10720)*100 = 49.5%

#Government-related discourse dominates COVID-19 conversations (49.5%), followed by lockdown (30.0%) and vaccination (20.5%) topics.
#This suggests that public sentiment is strongly centred on political leadership and institutional responses, rather than purely health-related themes.
#The large shift in results after expanding keywords highlights the importance of robust Boolean query design in accurately capturing social discourse.

In [ ]:
#Initial keyword queries can significantly underestimate topic prevalence.
#Expanding keyword sets to reflect how people actually communicate is essential for accurate social listening analysis.